version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_people
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:123123@postgres:5432/db_people
      JWT_SECRET_KEY: dkasndksandkasndksnkdsanksadnkn3knk
      PORT: 3000
    ports:
      - "4000:3000"
    depends_on:
      - postgres

  main-ui:
    build: 
      context: ./main-ui/
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000/api
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
