version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_people
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  people:
    build: ./
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:123123@postgres:5432/db_people
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  postgres-data:
